[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/qbeon/tmdwg-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  branch = "master"

[[constraint]]
  name = "github.com/fasthttp/websocket"
  version = "1.4.0"